services:

  mpu-mariadb:
    image: mariadb:10
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./gundul.cnf:/etc/mysql/mariadb.conf.d/gundul.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=jf8ehF38fkX
    restart: unless-stopped
    networks:
      - hub

networks:
  hub:
    external: true