services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
      - PLEX_CLAIM=claim-xxxxxxxxxxxxxxxxxxx
    #network_mode: host
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp 
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - ./data:/data
      - /mnt/movie1:/mnt/movie1
      - /mnt/movie2:/mnt/movie2
      - /mnt/serial:/mnt/serial