services:

  odoox:
    image: odoo:17
    restart: unless-stopped
    ports:
      - 10022:8069
    depends_on:
      - psqlx
    volumes:
      - ./odoox/etc-odoo:/etc/odoo
      - ./odoox/addons:/addons
      - odoox-var-lib-odoo:/var/lib/odoo
    environment:
      - HOST=psqlx
      - USER=odoogundul
      - PASSWORD=123
    
  psqlx:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - 10023:5432
    volumes:
      - psqlx-var-lib-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=odoogundul
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres

  pgadminx:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 10024:80
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@sofy.web.id
      PGADMIN_DEFAULT_PASSWORD: 123
    volumes:
      - pgadminx-var-lib-pgadmin:/var/lib/pgadmin
    configs:
     - source: servers.json
       target: /pgadmin4/servers.json

volumes:
  pgadminx-var-lib-pgadmin:
  odoox-var-lib-odoo:
  psqlx-var-lib-postgresql-data:

configs:
  servers.json:
    content: |
      {
        "Servers": {
            "1": {
                "Name": "Gundul",
                "Group": "Servers", 
                "Port": 5432,
                "Username": "odoogundul",
                "Host": "psqlx",
                "SSLMode": "disable",
                "MaintenanceDB": "postgres"
            }
        }
      }
