services:

  zabbixmysqlx:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./var-lib-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
    restart: unless-stopped

  zabbixserverx:
    image: zabbix/zabbix-server-mysql:alpine-7.2-latest
    ports:
      - 10051:10051
    depends_on:
      - zabbixmysqlx
    environment:
      DB_SERVER_HOST: zabbixmysqlx
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_USER: zabbixmysqluser
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_DATABASE: zabbixmysqldatabase
    restart: unless-stopped

  zabbixwebx:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.2-latest
    ports:
      - 8080:8080
    environment:
      ZBX_SERVER_HOST: zabbixserverx
      DB_SERVER_HOST: zabbixmysqlx
      MYSQL_USER: zabbixmysqluser
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_DATABASE: zabbixmysqldatabase
    restart: unless-stopped
