services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Jakarta
      - WEBUI_PORT=8080
      - TORRENTING_PORT=17234
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 8080:8080
#      - 17234:17234
#      - 17234:17234/udp
    restart: unless-stopped
    # user: "1001:1001"