services:
  app:
    image: docker.io/linkace/linkace:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./.env:/app/.env
      #- ./backups:/app/storage/app/backups
  db:
    image: docker.io/library/mariadb:12.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./db:/var/lib/mysql
  redis:
    image: docker.io/library/redis:8.2
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: unless-stopped
