services:

  web:
    image: nimdasx/nginx-php8-phalcon5
    restart: unless-stopped
    ports:
      - "10020:80"
      #- "2801:5173"
    volumes:
      - ./nginxphp/vhost.conf:/opt/docker/etc/nginx/vhost.conf
      - ./nginxphp/php-nimdasx.ini:/usr/local/etc/php/conf.d/php-nimdasx.ini
      - ./web:/web

  mariadb:
    image: mariadb:10
    ports:
      - 10021:3306
    volumes:
      - ./mariadb/var-lib-mysql:/var/lib/mysql
      - ./mariadb/gundul.cnf:/etc/mysql/mariadb.conf.d/gundul.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=sdFD8uhqCXPf0
    restart: unless-stopped
    
