name: ${PWD}

services:

  auth:
    image: caddy:alpine
    ports:
      - "9001:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - s3webui
    restart: unless-stopped

  s3webui:
    image: ghcr.io/wenisch-tech/s3webui:latest
    #ports:
    #  - "9001:8080"
    environment:
      S3_ACCESS_KEY: usernamekamu
      S3_SECRET_KEY: passwordkamu
      S3_ENDPOINT_URL: http://s3proxy:80
    restart: unless-stopped

  s3proxy:
    image: andrewgaul/s3proxy:latest
    ports:
      - "9000:80" # Ubah port host:container sesuai kebutuhan
    environment:
      # S3 Proxy config
      S3PROXY_AUTHORIZATION: "aws-v2-or-v4"    # authorization mode
      S3PROXY_IDENTITY: "usernamekamu"           # access key
      S3PROXY_CREDENTIAL: "passwordkamu"         # secret key
      S3PROXY_ENDPOINT: "http://0.0.0.0:80"    # endpoint
      S3PROXY_IGNORE_UNKNOWN_HEADERS: "true"
      
      # jclouds backend config
      #JCLOUDS_PROVIDER: "filesystem"           # penyimpanan lokal, ini deprecated yaaaa
      JCLOUDS_PROVIDER: "filesystem-nio2"
      JCLOUDS_FILESYSTEM_BASEDIR: "/data"      # lokasi bucket dir
        
      # (Optional) CORS
      S3PROXY_CORS_ALLOW_ALL: "true"
    volumes:
      - ./data:/data   # volume folder host untuk bucket
    restart: unless-stopped