services:
  php7phalcon3:
    image: nimdasx/apache-php7-phalcon3
    container_name: apachephp7phalcon3
    restart: unless-stopped
    #ports:
      #- 8080:80
    volumes:
      - ./var-www-html:/var/www/html
      - ./php-telo.ini:/usr/local/etc/php/conf.d/php-telo.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.a73.rule=Host(`xxx.xxx`)"
      - "traefik.http.routers.a73.entrypoints=websecure"
      - "traefik.http.routers.a73.tls.certresolver=myresolver"
    networks:
      - hub

networks:
  hub:
    external: true