services:
  fix-perms:
    image: alpine
    volumes:
      - ./var-opt-mssql:/var-opt-mssql
      - ./fix-perms.sh:/tmp/fix-perms.sh
    command: sh /tmp/fix-perms.sh
    restart: "no"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      fix-perms:
        condition: service_completed_successfully
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "hg34dgfhdgg"
      MSSQL_PID: "Developer"  # Bisa diganti ke "Express", "Standard", atau "Enterprise"
    volumes:
      - ./var-opt-mssql:/var/opt/mssql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "3471:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mssql
