services:
  netbird:
    image: netbirdio/netbird
    hostname: gantijadinamahostmu
    environment:
      - NB_SETUP_KEY=xqweqwesfasf
      - NB_MANAGEMENT_URL=https://afsafsaf.dsdsgdg
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    volumes:
      - ./var-lib-netbird:/var/lib/netbird
    restart: unless-stopped
    network_mode: host
