services:

  traefik:
    image: "traefik:v2.10"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./etc-traefik:/etc/traefik"
    networks:
      - hub

networks:
  hub:
    external: true