services:

  portainerxxx:
    container_name: portainer
    image: portainer/portainer-ee:latest
    restart: unless-stopped
    ports:
      - 8001:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    #networks:
      #- tersesat

#networks:
  #tersesat:
    #external: true