services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: gsgdg
      MINIO_ROOT_PASSWORD: gsdgsdhdhr
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"