services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - AGENTDVR_WEBUI_PORT=8090
      - TZ=Asia/Jakarta
    volumes:
      - ./media-xml:/AgentDVR/Media/XML
      - ./media-webserverroot-media:/AgentDVR/Media/WebServerRoot/Media
      - ./commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50010:50000-50010/udp
    restart: unless-stopped
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/media0:/dev/media0