services:
  nextcloud_db:
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=456
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - hub

  nextcloud_app:
    image: nextcloud
    restart: unless-stopped
    ports:
      - 2005:80
    links:
      - nextcloud_db
    volumes:
      - nextcloud_html:/var/www/html
    environment:
      - MYSQL_PASSWORD=456
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud_db
    networks:
      - hub

networks:
  hub:
    external: true

volumes:
  db_mysql:
  nextcloud_html: