version: '3.8'
services:
  nginxpm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginxpm-data:/data
      - nginxpm-letsencrypt:/etc/letsencrypt
    networks:
      - hub

networks:
  hub:
    external: true

volumes:
  data:
  letsencrypt:
