services:
  
  odoo16:
    image: odoo:16
    restart: unless-stopped
    ports:
      - 2001:8069
    depends_on:
      - postgres14
    volumes:
      - etc-odoo:/etc/odoo
      - mnt-extra-addons:/mnt/extra-addons
      - var-lib-odoo:/var/lib/odoo
    environment:
      - HOST=postgres14
      - USER=odoo16
      - PASSWORD=sr3rgdg6j
    networks:
      - hub
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=hub"
      - "traefik.http.routers.odoo16.rule=Host(`xxx.xxx.xxx.xxx`)"
      - "traefik.http.routers.odoo16.entrypoints=websecure"
      - "traefik.http.routers.odoo16.tls.certresolver=myresolver"
    
  postgres14:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 2002:5432
    volumes:
      - var-lib-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=odoo16
      - POSTGRES_PASSWORD=sr3rgdg6j
      - POSTGRES_DB=postgres
    networks:
      - hub

networks:
  hub:
    external: true

volumes:
  etc-odoo:
  var-lib-odoo:
  mnt-extra-addons:
  var-lib-postgresql-data: