services:
  zabbix-agent2:
    image: zabbix/zabbix-agent2
    ports:
      - 10050:10050
    volumes:
      - ./custom.conf:/etc/zabbix/zabbix_agent2.d/plugins.d/custom.conf
    restart: unless-stopped