services:
  redisx:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "akusehat"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  phpredisadminx:
    image: erikdubbelboer/phpredisadmin
    restart: unless-stopped
    ports:
      - 6380:80
    environment:
      - REDIS_1_HOST=redisx
      - REDIS_1_AUTH=akusehat
      - ADMIN_USER=redisadmin
      - ADMIN_PASS=duuniafanaakhiratselamanya
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"